name: Package and Release Azure Function

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-package:
    runs-on: ubuntu-latest  # Use windows-latest if you prefer

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'  # Adjust this to the .NET version you're using

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish --configuration Release --output ./publish

    - name: Package as ZIP
      run: |
        cd ./publish
        zip -r $GITHUB_WORKSPACE/functionapp.zip .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: functionapp.zip
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}